services:
  traefik:
    ports: !override []
    
    healthcheck:
      retries: !override 15
      start_period: !override 180s

networks:
  homelab_macvlan: !override
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.178.224/27
          gateway: 192.168.178.1
