services:
  traefik:
    ports: !override []
    
    healthcheck:
#      test: !override ["CMD-SHELL", "wget -q --spider http://localhost/ping || exit 1"]
      retries: !override 15
      start_period: !override 180s

networks:
  homelab_macvlan: !override
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
