# ${TRAEFIK_HOST}.${HOMELAB_DOMAIN}
# docker compose file for traefik

services:
  traefik:
    image: traefik:v3.7
    container_name: traefik-homelab
    restart: always
    networks:
      homelab_macvlan:
        ipv4_address: ${TRAEFIK_IP}  # fixe IP
      traefik_internal: {}

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    ports: 
      - "8111:80"
      - "58111:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro

    command:
      - "--configFile=/etc/traefik/traefik.yml"

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  step-ca:
    image: smallstep/step-ca
    container_name: step-ca
    restart: always
    user: "0:0"
    
    networks:
      - traefik_internal
    ports:
      - "59000:9000"
      
    volumes:
      - ./step:/home/step
      
    environment:
      - DOCKER_STEPCA_INIT_NAME=HomeLab CA
      - DOCKER_STEPCA_INIT_DNS_NAMES=step-ca,${HOMELAB_DOMAIN}
      - DOCKER_STEPCA_INIT_PASSWORD=${TRAEFIK_CA_PASSWORD}

    healthcheck:
      test: ["CMD", "step", "ca", "health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
  
networbraucks:
  homelab_macvlan:
    external: true
    
  traefik_internal:
    driver: bridge
