tls:
  certificates:
    - certFile: /certs/HomeLabCert.crt
      keyFile: /certs/HomeLabCert.key

http:

  routers:

    dashboard-http:

      rule: Host(`${TRAEFIK_HOST}.${HOMELAB_DOMAIN}`)

      entryPoints:
        - web

      middlewares:
        - redirect-to-https

      service: api@internal

    dashboard-https:

      rule: Host(`${TRAEFIK_HOST}.${HOMELAB_DOMAIN}`)

      entryPoints:
        - websecure

      tls: {}

      middlewares:
        - dashboard-auth

      service: api@internal

  middlewares:

    redirect-to-https:

      redirectScheme:
        scheme: https
        permanent: true

    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$4cv79qkr$fqKzPnmE3nX1pYXIhYq8u0" # Admin1$
          