http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    to-dashboard:
      redirectRegex:
        regex: ".*"
        # replace with proper domain and path to dashboard
        # replacement: "https://traefik.homelab.internal/dashboard/"
        replacement: "https://${TRAEFIK_HOST}.${HOMELAB_DOMAIN}/dashboard/"
        permanent: false