# ${ADGUARD_HOST}.${HOMELAB_DOMAIN}
# docker compose file for adguard

services:
  adguardhome:
    container_name: adguard-homelab
    # https://hub.docker.com/r/adguard/adguardhome/tags
    image: adguard/adguardhome:latest
    restart: unless-stopped
    networks:
      adguard_net:
        ipv4_address: ${ADGUARD_IP}  # fixe IP
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    ports:
      - "53:53/tcp"
      - "53:53/udp" # dns
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "${ADGUARD_PORT}:9080" # web-ui

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED}"
      - "traefik.http.routers.adguard.tls=${TRAEFIK_TLS_ENABLED}"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.rule=Host(`${ADGUARD_HOST}.${HOMELAB_DOMAIN}`)"      
      - "traefik.http.routers.adguard.loadbalancer.server.port=3000"
      
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:9080/control/status >/dev/null || exit 1"] 
      interval: 30s
      timeout: 10s
      retries: 8
      start_period: 30s

networks:
  adguard_net:
    driver: bridge
    ipam: 
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
